server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /queue {
        proxy_pass http://backend:3000;
    }

    location /add {
        proxy_pass http://backend:3000;
    }
}